# Default values for diamond-environment-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/yoshi-248909/diamond-environment-controller
  tag: 0.0.4
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

env: {}

secretEnv:
  GITHUB_ACCESS_TOKEN:
    github-credentials: token

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
