replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

env: {}

service:
  name: diamond-environment-controller
  type: LoadBalancer
  externalPort: 80
  internalPort: 3000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

secretEnv:
  GITHUB_ACCESS_TOKEN:
    github-credentials: token
