replicaCount: 1
image:
  repository: gcr.io/yoshi-248909/diamond-environment-controller
  tag: 0.0.31
  pullPolicy: IfNotPresent

env:
  ENV_REPO: https://github.com/tempo-bot/environment-yoshi104-production.git

secretEnv:
  GITHUB_ACCESS_TOKEN:
    github-credentials: token
  MASTER_SECRET:
    master-secret: password

service:
  name: diamond-environment-controller
  type: LoadBalancer
  externalPort: 80
  internalPort: 3000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

resources:
  limits:
    cpu: 400m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

